ram_sqlite:
  adapter: sqlite3
  database: /Users/ram/Workspace/jurnalo/JTier1-to-API/db/background_db.sqlite3

ram:
  adapter: mysql
  encoding: utf8
  database: background_db
  user: root
  password: 
  host: localhost

development:
    adapter: mysql
    encoding: utf8
    database: temp_db2
    username: root
    password: root
    socket: /var/run/mysqld/mysqld.sock

production:
    adapter: mysql
    encoding: utf8
    database: background_db_prod
    username: jurnalo
    password: jp4t2db
    host: 10.176.243.221