ram_sqlite:
  adapter: sqlite3
  database: /Users/ram/Workspace/jurnalo/JTier1-to-API/db/background_db.sqlite3

ram:
  adapter: mysql
  encoding: utf8
  database: background_db
  user: root
  password: 
  host: localhost
  reconnect: true

development:
  adapter: mysql
  encoding: utf8
  database: background_db
  user: root
  password: 
  host: localhost
  reconnect: true
  
cached:
  adapter: mysql
  encoding: utf8
  database: background_db
  user: root
  password: 
  host: localhost
  reconnect: true

production:
    adapter: mysql
    encoding: utf8
    database: background_db_prod
    username: jurnalo
    password: jp4t2db
    host: 10.176.243.221
    reconnect: true
    
justus:
  adapter: mysql
  encoding: utf8
  database: background_db_prod
  username: jurnalo
  password: jp4t2db
  host: 174.143.175.195
  reconnect: true