ram:
  adapter: mysql
  encoding: utf8
  database: tier2_db_dev
  username: root
  password: 
  host: localhost

development:
    adapter: mysql
    encoding: utf8
    database: tier2_db_dev
    username: root
    password: 
    host: localhost

cached:
  adapter: mysql
  encoding: utf8
  database: tier2_db_dev
  username: root
  password: 
  host: localhost
  

production:
    adapter: mysql
    encoding: utf8
    database: tier2_db_prod
    username: jurnalo
    password: jp4t2db
    host: 10.176.228.50
    reconnect: true

justus:
  adapter: mysql
  encoding: utf8
  database: tier2_db_prod
  username: jurnalo
  password: jp4t2db
  host: 174.143.172.95
