development:
    adapter: mysql
    encoding: utf8
    database: temp_db
    username: root
    password: root
    socket: /var/run/mysqld/mysqld.sock

production:
    adapter: mysql
    encoding: utf8
    database: tier2_db_prod
    username: jurnalo
    password: jp4t2db
    host: localhost
    socket: /var/lib/mysql/mysql.sock
